pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS'
    }
    
    environment {
        CI = 'true'
        VM_HOST = ''
        VM_USER = ''
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo '✅ Code récupéré'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'npm npm'
            }
        }
        
        stage('Test') {
            steps {
                sh 'npm test -- --coverage'
            }
        }
        
        stage('Build') {
            steps {
                sh 'npm run build'
                echo '✅ Build terminé'
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                script {
                    sh """
                        scp -r dist/* ${VM_USER}@${VM_HOST}:/var/www/html/
                    """
                    echo '🚀 Déployé sur la VM Azure !'
                }
            }
        }
    }
    
    post {
        success {
            echo '🎉 Pipeline frontend terminé !'
        }
        failure {
            echo '❌ Pipeline échoué'
        }
    }
}